### ISSUE TITLE
"Homepage" link in addons manager details page is the AMO URI "for Firefox" — even in SeaMonkey

### ISSUE THREAD

**Issue by tonymec** [glandium/about-startup#7]
Mozilla/5.0 (X11; Linux i686 on x86_64; rv:25.0) Gecko/20100101 Firefox/25.0 SeaMonkey/2.22a1 ID:20130712003003 c-c:1474fbd5ab3d m-c:b44898282f21

about:startup 0.1.12

"Homepage" link points to https://addons.mozilla.org/en-US/firefox/addon/about-startup/?src=api even when running in SeaMonkey.

**Comment by xabolcs** [comment]
To fix this  issue, @glandium should left out `/firefox` from the URL at the AMO admin page: https://addons.mozilla.org/en-US/addon/about-startup/

That will allow AMO to detect the application.

**Comment by tonymec** [comment]
@xabolcs commented: “To fix this issue, @glandium should left out <tt>/firefox</tt> from the URL at the AMO admin page: […]”

Then he might also want to leave out <tt>/en-US</tt> so the AMO page will appear in the user's preferred language.

**Comment by xabolcs** [comment]
Hmm... This isn't as easy as I thought. :-(

**Comment by glandium** [comment]
Then I have no idea what the issue is.

**Comment by xabolcs** [comment]
The problem is that `about:startup` page in Seamonkey points to the Firefox specific page of AMO.
See the tooltip on the picture below!

![aboutstartup_amo_homepage](https://f.cloud.github.com/assets/568751/861313/8acc34a0-f5cc-11e2-89d0-51ee80ba60b9.png)

Now I'm wondering about this is an AMO / Seamonkey (Toolkit?) bug, instead an `about:startup` configuration.
